# 项目信息
site_name: NovaWy
site_description: 个人技术博客
site_author:
site_url: https://blog.novawy.fun
docs_dir: content
strict: false

# 版权
copyright: 'Copyright &copy; 2026'

# 导航
nav:
  - 首页: index.md
  - 关于: about.md
  # - 样式演示: demo.md
  - 杂项:
    - 稀疏矩阵: 杂项/稀疏矩阵.md
  - 算法竞赛:
    - AtCoder:
      - Beginner Contest:
        - abc458: ShuaTi/AtCoder/AtCoder_Beginner_Contest/abc458.md
        - abc461: ShuaTi/AtCoder/AtCoder_Beginner_Contest/abc461.md
    - LeetCode:
      - 第11题: ShuaTi/LeetCode/11.md
      - 三数之和: ShuaTi/LeetCode/15.md
      - 接雨水: ShuaTi/LeetCode/42.md
      - 全排列: ShuaTi/LeetCode/46.md
      - 无重复字符的最长子串: ShuaTi/LeetCode/3.md
  - 课内课程:
    - Java: Classes/Java.md
    - 数据库: Classes/数据库.md
  - C++基础:
    - 字符串处理: CPP/String.md
    - 栈: CPP/Stack.md
    - 堆与优先队列: CPP/堆与优先队列.md
    - 双端队列: CPP/C++.md
    - vector: CPP/vector.md
    - map: CPP/map.md
    - set: CPP/set.md
    - bitset: CPP/bitset.md
# 主题
theme:
  name: material
  custom_dir: overrides

  language: 'zh'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: 切换暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: 切换亮色模式
  favicon: '_static/favicon.ico'
  icon:
    logo: 'material/school'
  features:
    - navigation.tabs
    - navigation.instant
    - content.code.copy

# 插件
plugins:
  - search:
      lang: zh
# 扩展
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

# 自定义样式和脚本
extra_css:
  - _static/css/typography.css
  - _static/css/navbar.css
  - _static/css/tables.css
  - _static/css/images.css
  - _static/css/404.css
extra_javascript:
  - _static/js/mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
